### ISSUE TITLE
Oppdatere lenke til Modenhetsmodell for orden i eget hus

### ISSUE THREAD

**Issue by tafjord** [Informasjonsforvaltning/veileder-orden-i-eget-hus#11]
Nåværende lenke: https://www.difi.no/fagomrader-og-tjenester/digitalisering-og-samordning/nasjonal-arkitektur/informasjonsforvaltning/modenhetsmodell-orden-i-eget-hus

Vi flytta over denne siden gjorde vi ikke @Elianne ?

**Comment by Elianne** [comment]
Stemmer: https://www.digdir.no/digitale-felleslosninger/modenhetsmodell-orden-i-eget-hus/2124

**Comment by tafjord** [comment]
Men selve modenhetsmodellen ser det ikke ut til at vi har flyttet? altså pdf.en.... https://www.difi.no/sites/difino/files/modenhetsmodell_-_oversikt_og_beskrivelse_av_egne_datasett_v1.0.pdf @Elianne

**Comment by tafjord** [comment]
Oooog... excelarket ligger visst også på difi-domenet: https://www.difi.no/sites/difino/files/modenhetsmodell_-_oversikt_og_beskrivelse_av_egne_datasett_v1.0.xlsx

**Comment by Elianne** [comment]
https://www.digdir.no/sites/sogn/files/2020-12/modenhetsmodell_-_oversikt_og_beskrivelse_av_egne_datasett_v1.0.xlsx

**Comment by tafjord** [comment]
Du kjører over selve modenhetsmodellen også? https://www.difi.no/sites/difino/files/modenhetsmodell_-_oversikt_og_beskrivelse_av_egne_datasett_v1.0.pdf

**Comment by Elianne** [comment]
https://www.digdir.no/sites/sogn/files/2020-12/modenhetsmodell_-_oversikt_og_beskrivelse_av_egne_datasett_v1.0.pdf

**Comment by tafjord** [comment]
Jeg har ikke redigeringstilgang så jeg får ikke oppdatert til de to sidene over på siden om modenhetsmodell. @Elianne @elihttps://www.digdir.no/digitale-felleslosninger/modenhetsmodell-orden-i-eget-hus/2124

**Comment by Elianne** [comment]
Nå har eg oppdatert lenkene.
