### ISSUE TITLE
Oppdatere lenke/flytte innhold til erfaringer fra Brreg

### ISSUE THREAD

**Issue by tafjord** [Informasjonsforvaltning/veileder-orden-i-eget-hus#13]
Dagens: https://www.difi.no/fagomrader-og-tjenester/digitalisering-og-samordning/nasjonal-arkitektur/informasjonsforvaltning/erfaringer-med-bestemme-hva-et-datasett-er-og-hvilke-datasett-som-skal-beskrives

**Comment by Elianne** [comment]
Eg skal opprette - kor høyrer den til? Kor skal den lenkast frå?

**Comment by tafjord** [comment]
Den lenkes til idag fra veileder Orden i eget hus. https://data.norge.no/guide/veileder-orden-i-eget-hus/#_hvor_starter_jeg

**Comment by Elianne** [comment]
https://www.digdir.no/digitale-felleslosninger/hva-er-et-datasett-og-hvilke-datasett-skal-beskrives/2198

Til info: Eg har endra litt på overskrifta.

**Comment by Elianne** [comment]
https://www.digdir.no/sites/sogn/files/2020-12/modenhetsmodell_-_oversikt_og_beskrivelse_av_egne_datasett_v1.0.pdf
