### ISSUE TITLE
Begrepet datasett

### ISSUE THREAD

**Issue by tafjord** [Informasjonsforvaltning/veileder-orden-i-eget-hus#14]
Vi lenker til DCAT-AP-NO, men definisjonen av datasett er fjernet fra siste versjon. Men definisjonen fra forrige versjon av dcat-ap-no finnes i begrepskatalogen (publisert av Brreg og Skatt), med forrige versjon av dcat-ap-no som kilde. https://data.norge.no/search-all?q=datasett. 

Jeg er usikker på hva som er best å gjøre i veilederen for Orden i eget hus. Fjerne henvisningen og definisjonen? https://data.norge.no/guide/veileder-orden-i-eget-hus/#_kartlegging

**Comment by jimjyang** [comment]
@tafjord Jeg syns hele avsnittet "I ordforklaringene ..." kan fjernes. Slik jeg leser det, er hensikten med dette avsnittet å forklare (eller "advare") at forrige versjon av DCAT-AP-NO hadde en for snever (IT-preget) definisjon av 'datasett'.

**Comment by tafjord** [comment]
fjernet den mer it-relaterte definisjonen
