### ISSUE TITLE
Oppdatere lenke til anbefalt modelleringsspråk - arbeidsprosesser

### ISSUE THREAD

**Issue by tafjord** [Informasjonsforvaltning/veileder-orden-i-eget-hus#16]
Idag lenker vi fra OiEH-veilederen hit: https://www.difi.no/fagomrader-og-tjenester/digitalisering-og-samordning/nasjonal-arkitektur/arkitekturbegreper

Er dette flyttet til digdir-domenet (finner det ikke der). Og hva er i så fall lenken?

**Comment by tafjord** [comment]
@Elianne Har sendt epost til Erik Hagen om saken. Beklager å hekte på deg, men jeg fikk inntrykk av at du hadde vært involvert i å flytte over arkitekturinnholdet også?

**Comment by Elianne** [comment]
Nei, lite involvert i akkurat den delen.
