### ISSUE TITLE
Definisjon av datasett

### ISSUE THREAD

**Issue by tafjord** [Informasjonsforvaltning/veileder-orden-i-eget-hus#20]
Dagens: Et datasett er en organisert samling av data. Brukes av NAV i begrepskatalogen. 

I begrepskatalogen fra Digdir: samling av data som er betraktet som en enhet

Referansene Brreg og Skatt bruker er ikke lenger gyldig, er hentet fra tidligere versjon av dcat.

**Comment by khvidsten** [comment]
Hensyntatt.
