### ISSUE TITLE
Oppdatere beskrivelse av API

### ISSUE THREAD

**Issue by tafjord** [Informasjonsforvaltning/veileder-orden-i-eget-hus#23]
https://data.norge.no/guide/veileder-orden-i-eget-hus/#_api_katalog_en_oversikt_over_grensesnitt_til_data

Trenger omarbeiding.

**Comment by stigbd** [comment]
Kva er det som treng omarbeiding? Er det avvik mellom

1. veileder og implementasjon (FDK), eller
2. veileder og spesifikasjon (DCAT-AP-NO), eller
3. begge deler?

Eg trenger litt meir å gå på.

**Comment by khvidsten** [comment]
Dette avsnittet om API-katalogen ble skrevet mens arbeidet med katalogen så vidt var i gang, og at teksten slik den er nå muligens ikke reflekterer "current state" i API-katalogen.

**Comment by khvidsten** [comment]
Hensyntatt.

**Comment by khvidsten** [comment]
Hensyntatt og lukket.
