### ISSUE TITLE
Inkludere begrep, api og infomodeller i kap om tilgjengeliggjøring av beskrivelser

### ISSUE THREAD

**Issue by tafjord** [Informasjonsforvaltning/veileder-orden-i-eget-hus#24]
https://data.norge.no/guide/veileder-orden-i-eget-hus/#_datakatalog_en_oversikt_over_datasett

Innholder kun informasjon om tilgjengeliggjøring av datasett

**Comment by khvidsten** [comment]
Hensyntatt.
