### ISSUE TITLE
Oppdatere avsnitt om virksomhetsintern datakatalog og lenke til kildekode for Felles datakatalog

### ISSUE THREAD

**Issue by tafjord** [Informasjonsforvaltning/veileder-orden-i-eget-hus#25]
Må skrives om: https://data.norge.no/guide/veileder-orden-i-eget-hus/#_lokal_datakatalog

**Comment by tafjord** [comment]
Denne siden på GitHub ser ut til å være utdatert: https://github.com/Informasjonsforvaltning/fdk/blob/develop/README.md

Finnes det en ny samleside som presenterer FDK for dem som vil installere løsningen lokalt? @stigbd

**Comment by khvidsten** [comment]
Hensyntatt i forvaltningsplanen.
