### ISSUE TITLE
kap om å beskrive data:  https://data.norge.no/guide/veileder-orden-i-eget-hus/#_beskrive_data

### ISSUE THREAD

**Issue by tafjord** [Informasjonsforvaltning/veileder-orden-i-eget-hus#30]
Burde antakelig skrives mer utfyllende ut over å peke på relevante standarder. F.eks finne eksempler på prosess ved beskrivelser og hvordan det gjøres med ulike verktøy etc. Generelle anbefalinger og/eller erfaringer på hvordan jobbe med beskrivelser. Konvertere til riktig format er mer "siste finish"?

**Comment by khvidsten** [comment]
Hensyntatt.
