### ISSUE TITLE
Linjeskiftfeil i asciidoctor kildefilen

### ISSUE THREAD

**Issue by skibohemen** [Informasjonsforvaltning/veileder-orden-i-eget-hus#38]
Ref https://data.norge.no/guide/veileder-orden-i-eget-hus/ - bla litt nedover så ser man flere forekomster av mellomoverskrifter som er blitt tolket som plain tekst av adoc parser, feks.

=== Oppbygging av veilederen

Kan være pga innledende space eller manglende linjeskift før oversrkiften

**Comment by tafjord** [comment]
Takk! Var et lite mysterium, men det ordnet seg med å legge in space i main-fila. Nå skal det være i orden.
