### ISSUE TITLE
[publisering] PDF-filnavnet bør gjenspeile veilederens navn

### ISSUE THREAD

**Issue by jimjyang** [Informasjonsforvaltning/veileder-orden-i-eget-hus#43]
Navnet til PDF-filen som kan lastes ned er nå "document.pdf". 

Ønsker å ha et filnavn som gjenspeile veilederens navn, f.eks. repo-navnet (som også brukes i URLen til den gjeldende versjonen på data.norge.no).

**Comment by stigbd** [comment]
Fiksa i 84c4bb62b41ed1d695d9da48a832980d886060c7

**Comment by jimjyang** [comment]
Fiksa
