### ISSUE TITLE
Tilgangsnivå for datasett avviker fra EUs definisjoner

### ISSUE THREAD

**Issue by jimjyang** [Informasjonsforvaltning/veileder-orden-i-eget-hus#44]
Se https://github.com/Informasjonsforvaltning/dcat-ap-no/issues/418

Gjelder avsnittet [Vurdering av tilgangsnivå](https://data.norge.no/guide/veileder-orden-i-eget-hus/#_vurdering_av_tilgangsniv%C3%A5)

**Comment by khvidsten** [comment]
Hensyntatt.
