### ISSUE TITLE
Flytte "samboer" ppx over til digdir-domene

### ISSUE THREAD

**Issue by tafjord** [Informasjonsforvaltning/veileder-orden-i-eget-hus#8]
Denne lenkes det til i veilederen. Må flyttes over....

https://www.difi.no/files/samboerpptx

**Comment by Elianne** [comment]
Lasta opp til digdir.no-domenet

**Comment by Elianne** [comment]
https://www.digdir.no/sites/sogn/files/2020-12/samboer.pptx

**Comment by Elianne** [comment]
https://www.digdir.no/digitale-felleslosninger/samboerpptx/2157

**Comment by tafjord** [comment]
Takk Elianne! Ny lenke: https://www.digdir.no/digitale-felleslosninger/powerpoint-med-samboereksempel/2157
